# Generated by Django 4.2.4 on 2023-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=20)),
                ('email', models.EmailField(error_messages={'unique': 'This email address is already in use.'}, max_length=200, unique=True)),
                ('fathers_name', models.CharField(max_length=200)),
                ('mothers_name', models.CharField(max_length=200)),
                ('present_address', models.CharField(max_length=200)),
                ('permanant_address', models.CharField(max_length=200)),
                ('personal_contact_no', models.CharField(max_length=15)),
                ('guardians_contact_no', models.CharField(max_length=15)),
                ('favourite_color', models.CharField(max_length=20)),
                ('t_shirt_size', models.CharField(max_length=15)),
                ('hobby', models.CharField(max_length=200)),
                ('aim_in_life', models.CharField(max_length=200)),
                ('comment_type', models.CharField(choices=[('advice', 'Advice'), ('complain', 'Complain')], max_length=10)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student Info',
            },
        ),
    ]
