# Generated by Django 4.2.4 on 2023-08-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('fathers_name', models.CharField(max_length=200)),
                ('mothers_name', models.CharField(max_length=200)),
                ('present_address', models.CharField(max_length=200)),
                ('permanant_address', models.CharField(max_length=200)),
                ('personal_contact_no', models.CharField(max_length=15)),
                ('gurdians_contact_no', models.CharField(max_length=15)),
                ('t_shirt_size', models.CharField(max_length=15)),
                ('hobby', models.CharField(max_length=200)),
                ('aim_in_life', models.CharField(max_length=200)),
            ],
        ),
    ]
